CREATE DATABASE LOGIN;
USE LOGIN;

CREATE TABLE USERS (UNAME VARCHAR(20),EMAIL VARCHAR(20),UPASSWORD INT , CFMPASSOWRD INT);
INSERT INTO USERS VALUES("Senthil","senthil@gmail.com",2002,2002);
ALTER TABLE USERS DROP COLUMN CFMPASSOWRD;
SELECT * FROM USERS;
